### ISSUE TITLE
stopped work

### ISSUE THREAD

**Issue by pwnyprod** [manahter/ulauncher-translate#1]
doesnt work after fresh installed ulauncher.

**Comment by nesivmi** [comment]
Şimdi denedim. Herhangi bir sorun tespit edemedim. Her şey benim için iyi görünüyor. Hatayı paylaşırsanız tekrar bakarım.

**Comment by nesivmi** [comment]
> doesnt work after fresh installed ulauncher.

I tried now. I couldn't detect any problems. Everything looks good to me. If you share the error, I'il look again.

**Comment by nesivmi** [comment]
> doesnt work after fresh installed ulauncher.

**Comment by pwnyprod** [comment]
ok im really sorry :D now it works for me. It was the day i started with ulauncher5, maybe i did something wrong or something wasnt up after install. Now it works great, ty ya.
