### ISSUE TITLE
No result

### ISSUE THREAD

**Issue by shakir85** [manahter/ulauncher-translate#2]
The extension keeps loading with no result: Ubuntu 19.10 - Gnome Shell 3.34.3

**Comment by nesivmi** [comment]
Hello there. Have you tried deleting and reinstalling?
I did not encounter any problems while using Ubuntu 19.10
This text was written with this extension

**Comment by nesivmi** [comment]
> The extension keeps loading with no result: Ubuntu 19.10 - Gnome Shell 3.34.3

Hello there. Have you tried deleting and reinstalling?
I did not encounter any problems while using Ubuntu 19.10
This text was written with this extension

**Comment by shakir85** [comment]
Yes.. now it works. Reinstalling fixed the issue. Thank you!
