### ISSUE TITLE
Constantly loading

### ISSUE THREAD

**Issue by samuel-constantino** [manahter/ulauncher-translate#5]
The program does not load the translation

> > O programa não carrega a tradução
> 
> Se você enviar a captura de tela "Preferências", irei olhar

https://ibb.co/c8Q1GJV

**Comment by manahter** [comment]
> The program does not load the translation

**Comment by manahter** [comment]
> The program does not load the translation

If you send the "Preferences" screenshot, I will look

**Comment by manahter** [comment]
One also this plugin only works depending on the Internet.

**Comment by manahter** [comment]
> The program does not load the translation
> 
> > > O programa não carrega a tradução
> > 
> > 
> > Se você enviar a captura de tela "Preferências", irei olhar
> 
> https://ibb.co/c8Q1GJV

**Step 1:
Go to link:**
https://translate.google.com/m?sl=en&tl=es&hl=en&q=How+are+you%3F
>![resim](https://user-images.githubusercontent.com/73780835/114312741-644aec80-9afc-11eb-8ab2-895e2a0356c1.png)

**Is the image like that?** 

**Step 2:
Go to -> Ulauncher -> Prefrences -> Extension:**
![asda](https://user-images.githubusercontent.com/73780835/114312826-b8ee6780-9afc-11eb-9b67-f61eba74738f.png)

**Please send a picture like this**

**Comment by samuel-constantino** [comment]
I tried again today and it worked! I believe it didn't work before because of the slow internet.
